export const arabic = {
  hello: "مرحبا",
  shop: "تسوق",
  dine: "المطاعم",
  entertain: "الترفيه",
  cinema: "أفلام",
  event: "الفعاليات",
  services: "الخدمات",
  offers: "العروض",
  "opening hours": "ساعات العمل",
  careers: "وظائف",
  "contact us": "اتصل بنا",
  "about us": "نبذة عنا",
  advertising: "الإعلانات",
  leasing: "إيجار",
  "mall map": "خريطة المكان",
  ع: "En",
  "tanta gharbia egypt": "طنطا الغربية مصر",
  "Mall of Tanta": "مول طنطا",
  "Billy Beez": "بيلي بيز",
  Spinneys: "سباينيز",
  "Galaxy cinema": "سينما غالاكسي",
  "The first unconventional mall of its kind, located in Tanta. Mall of Tanta rolls out on a vast area to introduce a distinctive retail world blending both local and international brands under one roof":
    "أول مول غير تقليدي من نوعه ، يقع في طنطا ، مول طنطايمتد على مساحة واسعة لتقديم عالم تجزئة مميز يمزج بين العلامات التجارية المحلية والعالمية تحت سقف واحد",
  "Billy Beez is an indoors playground with lots of safe games and activities. The Play area has lots of big slides, wall climbing and games that even the older kids will enjoy":
    "بيلى بيز عباره عن منطقة ملاعب مغطاه للأطفال من سن 3 سنوات حتي 12 سنه كما تضم ثلاثة ملاعب لممارسة كرة القدم ويمكن للأباء مشاركة أبنائهم اللعب فيها، وعربات البلازما، وزحاليق قصيرة وطويلة، وتحتوي علي عدة متاهات وممرات يستطيع الأطفال الدخول فيها والإستمتاع بها، كما أنهم يمكنهم الصعود والتسلق على السلالم وممارسة الألعاب في بيت الكرات وبها منطقة تسلق للأطفال من 7سنوات إلى 12 سنة.",
  "The first & biggest cinema at Tanta with international specs, presenting international & 3d movies.":
    "سينما جالاكسى بمول طنطا أكبر دور عرض سينمائى بطنطا",
  "Spinneys is Egypt’s premier purveyor of the finest quality food and household goods for families to enjoy the benefits of healthy living, with freshness and world-class service at the heart of our daily operations":
    "منذ ٩٠ عاما وتحديدا في عام ١٩٢٤ أسس السيد/ آرثر سبينى أول محل يحمل اسم سبينيس في مدينة الإسكندرية ليبيع من خلاله جميع أنواع البقالة والمخبوزات والمنتجات الغذائية المختلفة ووضع معاييرجودة صارمة حيث الالتزام بأعلى مستوى جودة وبأسعار معقولة مع توفيير كافة عناصر التسوق الممتع لرواد المحل.",
  "Scroll Down": "حرك للأسفل",
  "Opening Time": "أوقات الدوام",
  Pharmacy: "الصيدلية ",
  Health: "الصحة",
  Beauty: "الجمال",
  Fitness: "رياضة ولياقة بدنية",
  Cosmetics: "مستحضرات تجميل",
  Perfumes: "عطور",
  Household: "أدوات منزلية",
  Furniture: "أثاث",
  Carpet: "سجاد",
  "Home Accessories": "اكسسوارات منزلية",
  Texttile: "أقمشة",
  "Sports Wear": "ألبسة رياضية",
  Fashoin: "موضة",
  Books: "الكتب",
  Stationery: "بطاقات",
  Toys: "قرطاسية",
  Games: "ألعاب",
  Gifts: "هدايا",
  Elctronic: "إلكترونيات",
  "Home Applainces": "أدوات منزلية",
  Computers: "حاسب اّلي",
  Mobailes: "هواتف نقالة",
  Resturants: "المطاعم",
  "Cofee Shop": "المقاهي",
  Specialty: "مطاعم متخصصة",
  "Fast Food": "وجبات سريعة",
  Other: "المزيد",
  "view All Group Entities": "عرض جميع كيانات المجموعة",
  Copyright: "حقوق الطبع والنشر",
  Marakez: "مراكز",
  "All Rights Reserved": "جميع الحقوق محفوظة",
  "Privacy Policy": "سياسة الخصوصية",
  "What's Happening": "ماذا يحدث",
  "Mazaya Now Open!": "مزايا أفتتح الاّن!",
  "Your summer just got a lot more exciting at MOT!":
    "لقد أصبح صيفك أكثر إثارة في مول طنطا",
  "you can now enjoy your shopping experience":
    "يمكنك الاّن الإستمتاع بتجربة التسوق الخاصة بك",
  Mazaya: "مزايا",
  "MOT Summer Sale": "تخفيضات مول طنطا",
  WIFI: "واي فاي",
  "Connect to submit your leasing interest in our shopping malls":
    "تواصل لتقديم اهتمامك التأجيري في مراكز التسوق لدينا.",
  "Mall of Tanta offers your business unlimited media options to advertise and promote your brand":
    "مول طنطا يقدم لشركتك خيارات إعلامية غير محدودة للإعلان والترويج لعلامتك التجارية",
  "See more": "شاهد المزيد",
  "The ultimate shopping destination.": "وجهة التسوق النهائية.",
  "Pharmacy/ Health/ Beauty/ Fitness/ Cosmetics/ Perfumes":
    "صيدليات/صحة / جمال /لياقة /مستحضرات تجميل/عطور",
  "Electronics/Home Appliances/ Computers/ Mobiles":
    "أجهزة الكترونية/أدوات منزلية/حواسيب/هواتف نقالة",
  "Books / Stationery / Toys / Games / Gifts": "كتب/بطاقات/قرطاسية/ألعاب/هدايا",
  "Household /Furniture /Carpet / Home Accessories/ Textile":
    "أدوات منزلية/أثاث/سجاد/إكسسوارات منزلية/أقمشة",
  Fashion: "موضة",
  "Sport Wear": "ألبسة رياضية",
};
