export const english = {
  hello: "Hello",
  shop: "SHOP",
  dine: "Dine",
  entertain: "Entertain",
  cinema: "Cinema",
  event: "Events",
  services: "Services",
  offers: "Offesr",
  "opening hours": "Opening Hours",
  careers: "Careers",
  "contact us": "Contact Us",
  "about us": "About Us",
  advertising: "Advertising",
  leasing: "Leasing",
  "mall map": "Mall Map",
  ع: "ع",
  "tanta gharbia egypt": "Tanta,Gharbia,Egypt",
  "Mall of Tanta": "Mall of Tanta",
  "Billy Beez": "Billy Beez",
  Spinneys: "Spinneys",
  "Galaxy cinema": "Galaxy cinema",
  "The first unconventional mall of its kind, located in Tanta. Mall of Tanta rolls out on a vast area to introduce a distinctive retail world blending both local and international brands under one roof":
    "The first unconventional mall of its kind, located in Tanta. Mall of Tanta rolls out on a vast area to introduce a distinctive retail world blending both local and international brands under one roof",
  "Billy Beez is an indoors playground with lots of safe games and activities. The Play area has lots of big slides, wall climbing and games that even the older kids will enjoy":
    "Billy Beez is an indoors playground with lots of safe games and activities. The Play area has lots of big slides, wall climbing and games that even the older kids will enjoy",
  "The first & biggest cinema at Tanta with international specs, presenting international & 3d movies.":
    "The first & biggest cinema at Tanta with international specs, presenting international & 3d movies.",
  "Spinneys is Egypt’s premier purveyor of the finest quality food and household goods for families to enjoy the benefits of healthy living, with freshness and world-class service at the heart of our daily operations":
    "Spinneys is Egypt’s premier purveyor of the finest quality food and household goods for families to enjoy the benefits of healthy living, with freshness and world-class service at the heart of our daily operations",
  "Scroll Down": "Scroll Down",
  "Opening Time": "opening Time",
  Pharmacy: "Pharmacy",
  Health: "Health",
  Beauty: "Beauty",
  Fitness: "Fitness",
  Cosmetics: "Cosmetics",
  Perfumes: "Perfumes",
  Household: "Household",
  Furniture: "Furniture",
  Carpet: "Carpet",
  "Home Accessories": "Home Accessories",
  Texttile: "Texttile",
  "Sports Wear": "Sports Wear",
  Fashoin: "Fashoin",
  Books: "Books",
  Stationery: "Stationery",
  Toys: "Toys",
  Games: "Games",
  Gifts: "Gifts",
  Elctronic: "Elctronic",
  "Home Applainces": "Home Applainces",
  Computers: "Computers",
  Mobailes: "Mobailes",
  Resturants: "Resturants",
  "Cofee Shop": "Cofee Shop",
  Specialty: "Specialty",
  "Fast Food": "Fast Food",
  Other: "Other",
  "view All Group Entities": "view All Group Entities",
  Copyright: "Copyright",
  Marakez: "Marakez",
  "All Rights Reserved": "All Rights Reserved",
  "Privacy Policy": "Privacy Policy",
  "What's Happening": "What's Happening",
  "Mazaya Now Open!": "Mazaya Now Open!",
  "Your summer just got a lot more exciting at MOT!":
    "Your summer just got a lot more exciting at MOT!",
  "you can now enjoy your shopping experience":
    "you can now enjoy your shopping experience",
  Mazaya: "Mazaya",
  "MOT Summer Sale": "MOT Summer Sale",
  WIFI: "WIFI",
  "Connect to submit your leasing interest in our shopping malls":
    "Connect to submit your leasing interest in our shopping malls",
  "Mall of Tanta offers your business unlimited media options to advertise and promote your brand":
    "Mall of Tanta offers your business unlimited media options to advertise and promote your brand",
  "See more": "See more",
  "The ultimate shopping destination.": "The ultimate shopping destination.",
  "Pharmacy/ Health/ Beauty/ Fitness/ Cosmetics/ Perfumes":
    "Pharmacy/ Health/ Beauty/ Fitness/ Cosmetics/ Perfumes",
  "Electronics/Home Appliances/ Computers/ Mobiles":
    "Electronics/Home Appliances/ Computers/ Mobiles",
  "Books / Stationery / Toys / Games / Gifts":
    "Books / Stationery / Toys / Games / Gifts",
  "Household /Furniture /Carpet / Home Accessories/ Textile":
    "Household /Furniture /Carpet / Home Accessories/ Textile",
  Fashion: "Fashion",
  "Sport Wear": "Sport Wear",
};
